services:
  create:
    build:
      context: .
      dockerfile: Dockerfile.create
    volumes:
      - ./certs/:/app/certs/
      - ./keys/:/app/keys/
  nginx:
    image: nginx:1.25
    ports:
      - "443:443"
    volumes:
      - ./certs/:/etc/nginx/certs/
      - ./keys/:/etc/nginx/keys/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - create
